name: Testing Pull Request
on:
  pull_request:
    types: [synchronize, opened, reopened]
jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --prefer-dist
      - name: Laravel Pint Dry Run
        run: ./vendor/bin/pint -v --test
